# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Install dependencies"
      run: yarn install --frozen-lockfile
    - name: "Create env file"
      uses: SpicyPizza/create-envfile@v2.0
      with:
        file_name: .env.test
        envkey_NODE_ENV: TEST
        envkey_JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        envkey_JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
        envkey_TOKEN_EXPIRATION: ${{ secrets.TOKEN_EXPIRATION }}
        envkey_DATABASE_USER: ${{ secrets.DATABASE_USER }}
        envkey_DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
        envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
    - name: "Run tests"
      run: |
        yarn test
        

        